### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by furynick** [christianwach/civicrm-wp-member-sync#10] opened 2016-02-10 21:09 UTC
Hi,

Can you please add ability to add any new wordpress user to a civicrm contact group ?

Thanks for your time, I'll try to make some code proposals if I can understand the best way to achieve it.

**Comment by christianwach** [comment] 2016-02-10 21:11
@furynick This seems to be a duplicate of #9 - are the suggestions there of any use to you?

**Comment by furynick** [comment] 2016-02-10 21:36
Well, I'm using Simple:Press so no BP plugin can suit to my need.
I don't want to synchronize groups but only add a WP user to a default CiviCRM contact group.
I'm using this for mailing purpose to new users from time to time and don't want to forget one because it wasn't added to that group.
Didn't find the way in CiviCRM to get a list of all users not belonging to any group.

**Comment by christianwach** [comment] 2016-02-11 10:42
> Well, I'm using Simple:Press so no BP plugin can suit to my need.

Hmm, not sure that's true - it seems that Simple:Press are quite proud of [their BuddyPress integration](http://simple-press.com/documentation/codex/plugins/our-plugins/available-plugins/buddypress/).

> I don't want to synchronize groups but only add a WP user to a default CiviCRM contact group.

If this is the case, I don't quite see how this plugin fits your requirements. However, I do think it's a nice idea for a separate plugin that does what you're after. Please feel free to reuse any code you find here for your purposes.

**Comment by christianwach** [comment] 2016-03-31 16:10
Closed due to inactivity

**Closed by christianwach** 2016-03-31 16:10 UTC
